// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Interprets player commands and updates the game state.
 *
 * - interpretPlayerCommand - A function that interprets player commands.
 * - InterpretPlayerCommandInput - The input type for the interpretPlayerCommand function.
 * - InterpretPlayerCommandOutput - The return type for the interpretPlayerCommand function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const InterpretPlayerCommandInputSchema = z.object({
  command: z.string().describe('The player command to interpret.'),
  gameState: z.string().describe('The current game state as a JSON string.'),
});
export type InterpretPlayerCommandInput = z.infer<typeof InterpretPlayerCommandInputSchema>;

const InterpretPlayerCommandOutputSchema = z.object({
  action: z.string().describe('The action to take based on the command.'),
  updatedGameState: z.string().describe('The updated game state as a JSON string.'),
  narration: z.string().describe('A narration of the action taken and its consequences, to be displayed to the player.'),
});
export type InterpretPlayerCommandOutput = z.infer<typeof InterpretPlayerCommandOutputSchema>;

export async function interpretPlayerCommand(
  input: InterpretPlayerCommandInput
): Promise<InterpretPlayerCommandOutput> {
  return interpretPlayerCommandFlow(input);
}

const interpretPlayerCommandPrompt = ai.definePrompt({
  name: 'interpretPlayerCommandPrompt',
  input: {
    schema: z.object({
      command: z.string().describe('The player command to interpret.'),
      gameState: z.string().describe('The current game state.'),
    }),
  },
  output: {
    schema: z.object({
      action: z.string().describe('The action to take based on the command.'),
      updatedGameState: z.string().describe('The updated game state as a JSON string.'),
      narration: z.string().describe('A narration of the action taken and its consequences, to be displayed to the player.'),
    }),
  },
  prompt: `You are the Dungeon Master of a text-based adventure game. The player has issued the following command: {{{command}}}.

The current game state is: {{{gameState}}}

Based on the command and the game state, determine the action the player is trying to take. Update the game state to reflect the results of that action.  Finally, narrate the results of the action to the player, limiting the narration to a maximum of 2 paragraphs. At the end of the narration, always ask the player what they want to do next.

Return the action, updated game state and narration in the JSON format described. Make sure that updatedGameState is valid JSON.`,
});

const interpretPlayerCommandFlow = ai.defineFlow<
  typeof InterpretPlayerCommandInputSchema,
  typeof InterpretPlayerCommandOutputSchema
>({
  name: 'interpretPlayerCommandFlow',
  inputSchema: InterpretPlayerCommandInputSchema,
  outputSchema: InterpretPlayerCommandOutputSchema,
},
async input => {
  const {output} = await interpretPlayerCommandPrompt(input);
  return output!;
});
